### ISSUE TITLE
A RenderFlex overflowed by 15 pixels on the bottom.

### ISSUE THREAD

**Issue by gitboss** [nisrulz/flutter-examples#1]
The following error is raised in case you tilt the phone - 

I/FlutterActivityDelegate(13663): onResume setting current activity to this
I/flutter (13663): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13663): The following message was thrown during layout:
I/flutter (13663): A RenderFlex overflowed by 15 pixels on the bottom.
I/flutter (13663): 
I/flutter (13663): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter (13663): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter (13663): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter (13663): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter (13663): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter (13663): This is considered an error condition because it indicates that there is content that cannot be
I/flutter (13663): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter (13663): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter (13663): like a ListView.
I/flutter (13663): The specific RenderFlex in question is:
I/flutter (13663):   RenderFlex#ff4a0 relayoutBoundary=up2 OVERFLOWING
I/flutter (13663):   creator: Column ← Center ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (13663):   CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (13663):   _InkFeatures-[GlobalKey#87c38 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (13663):   PhysicalModel ← ⋯
I/flutter (13663):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (13663):   constraints: BoxConstraints(0.0<=w<=698.2, 0.0<=h<=316.7)
I/flutter (13663):   size: Size(698.2, 316.7)
I/flutter (13663):   direction: vertical
I/flutter (13663):   mainAxisAlignment: start
I/flutter (13663):   mainAxisSize: max
I/flutter (13663):   crossAxisAlignment: stretch
I/flutter (13663):   verticalDirection: down
I/flutter (13663): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter (13663): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by nisrulz** [comment]
@gitboss which flutter example?

**Comment by gitboss** [comment]
@nisrulz The error is in this example - Stateless Widget - https://github.com/nisrulz/flutter-examples/tree/master/stateless_widgets

**Comment by nisrulz** [comment]
I will check this by EOD today. Will try and push the fixed version

**Comment by nisrulz** [comment]
Fixed now.

**Comment by talamaska** [comment]
@nisrulz Man, that fix made my day, whole day wondering what the hell is going on with my StreamBuilder and my widgets. I was making some No_data widget and error_message widget, when I decided to put a column to arrange my icon and text vertically. Will keep this SingleChildScrollView in my favorites :)
