### ISSUE TITLE
Example Request: Firebase_auth with google and facebook SignIn

### ISSUE THREAD

**Issue by Sriraj-dev** [nisrulz/flutter-examples#101]
hey @nisrulz , Can I contribute to this repo with an app supporting firebase authentication with google and facebook signIn under Hacktoberfest?

**Comment by nisrulz** [comment]
Yes, that would a possible example app.

**Comment by JaredEzz** [comment]
I'd be happy to do this is @Sriraj-dev doesn't deliver. I've shipped multiple apps using Google, Facebook, GitHub, and other OAuth providers with FirebaseAuth

**Comment by nisrulz** [comment]
@JaredEzz the core idea is mentioned here: https://github.com/nisrulz/flutter-examples/issues/21#issuecomment-707645002

**Comment by Utkarsh4517** [comment]
can i still work on this issue as it is open?
