### ISSUE TITLE
Example Request: BMI calculator

### ISSUE THREAD

**Issue by SoulPlayer23** [nisrulz/flutter-examples#103]
Hey, 
     I would like to contribute to this repository a simple BMI calculator app. It takes height and weight and shows the BMI and gives a remark on your weight.

**Comment by suyoscar11** [comment]
Hey!! I would like to contribute on this project!! Can you please assign it to me?? Thanks:)

**Comment by akash-kd** [comment]
Hey Is this still Open? Can you Assign it to me ??

**Comment by lutaii** [comment]
Hello! I would like to contribute on this projects if it's relevant. Can you please assign it to me? Thank you

**Comment by Mandeep56Singh** [comment]
@lutaii  are you still working on it ?

**Comment by lutaii** [comment]
@Mandeep56Singh yes

**Comment by sajjadrahman56** [comment]
Greetings .
I would like to contribute . Can I ?

**Comment by nisrulz** [comment]
@sajjadrahman56 Because https://github.com/nisrulz/flutter-examples/pull/130 already exists, so this issue is already assigned and worked up.

**Comment by sajjadrahman56** [comment]
Oh , looking forward . Thank you

**Comment by nisrulz** [comment]
PR https://github.com/nisrulz/flutter-examples/pull/130 is merged now. Closing this issue.
