### ISSUE TITLE
404 - [ flutter-examples/push_notifications ] Link is broken

### ISSUE THREAD

**Issue by sajjadrahman56** [nisrulz/flutter-examples#135]
Greetings,

Thank you for the amazing collection of Flutter code. I visited some of the links mentioned in the Readme.md file. However, when I clicked on the link [push_notifications](https://github.com/nisrulz/flutter-examples/blob/develop/push_notifications), it displayed a **404 error**.

**Comment by nisrulz** [comment]
Thank you for reporting. I'll take a look into it.

**Comment by nisrulz** [comment]
This is fixed now.
