### ISSUE TITLE
Example request: Analytics Integration

### ISSUE THREAD

**Issue by nisrulz** [nisrulz/flutter-examples#20]
Project Name: analytics_integration
Description: A flutter example app to setup analytics such as Google Analytics.

**Comment by hiashutoshsingh** [comment]
@nisrulz Hey Nishant, I would like to work on this issue.

**Comment by hiashutoshsingh** [comment]
@nisrulz Hey Nishant, did you got a chance to have a look on this.

**Comment by nisrulz** [comment]
PR #76 was merged. Closing this issue.
