### ISSUE TITLE
Example request: Push Notification Integration

### ISSUE THREAD

**Issue by nisrulz** [nisrulz/flutter-examples#23]
Project Name:  push_notifications
Description: A flutter example app to setup firebase push notifications

**Comment by cv692001** [comment]
Hey , I am willing to my first contribution can you please help me out in this , It will be very nice of you :)

**Comment by nisrulz** [comment]
Hello @cv692001 do you want to contribute to adding a Flutter example app that does has Push notifications? 
If yes, then simply create an sample app and open a PR. Make sure to follow the guidelines [here](https://github.com/nisrulz/flutter-examples#pull-requests)

**Comment by tejasbirsingh** [comment]
I would like to work on this. I have recently implemented push notification in my flutter app. Just brief me about what type of example should I work on ? Thanks

**Comment by nisrulz** [comment]
@tejasbirsingh I can assign this issue to you so you can start working on this.

The idea is simple:

Simply integrate firebase push notification using [FlutterFire plugin](https://firebaseopensource.com/projects/firebaseextended/flutterfire/packages/firebase_messaging/readme)

Because it is firebase, it should work for both Android and iOS.

**Comment by tejasbirsingh** [comment]
I will integrate Firebase Cloud Functions With flutter app. Those who will see the example from this repository will have to add their own google-services.json file rest all dependencies will be there. Is it right?
If yes you can assign me the task. Thanks

**Comment by tejasbirsingh** [comment]
Hey ! In hacktoberfest this repository is shown as Ineligible. Maybe you should see to it. Thanks
![image](https://user-images.githubusercontent.com/48317772/95089477-d0115e80-0741-11eb-8249-e4867986e701.png)

**Comment by tejasbirsingh** [comment]
Now its not showing ineligible. Thanks @nisrulz !!

**Comment by Nischint2003** [comment]
hey I was keen about to do a flutter example app for push notification , so I did a chatapp with the push notification integrated .

**Comment by nisrulz** [comment]
@Nischint2003 please always get approval from maintainer in an issue (open a new one if there isn't one open) before you open a PR.

Even though you have opened a PR #139, it is not actually useful for this repo because an example already exists inside the repository: https://github.com/nisrulz/flutter-examples/blob/develop/push_notifications

That said, this issue should have been closed by now but somehow it didn't come to my notice, until today. Closing this issue now.
