### ISSUE TITLE
Example request: Unit Testing

### ISSUE THREAD

**Issue by nisrulz** [nisrulz/flutter-examples#26]
Project Name:  unit_testing
Description: A flutter example app to demonstrate unit testing.

**Comment by GajjarMiten** [comment]
@nisrulz, I would like to work on it.

**Comment by nisrulz** [comment]
@GajjarMiten nice. 

First suggest the idea of the app here, then mention what all you will be covering with unit testing.

Also make sure to follow contribution guidelines in the readme.

**Comment by GajjarMiten** [comment]
hey @nisrulz,
we can add an app in which user have to do sign in and then it shows some tourist places by fetching location from a dummy API.

I will create unit tests for sign-in form validator class and for a class which calls dummy API for fetching locations.

I will follow the contribution guidelines.

**Comment by nisrulz** [comment]
Sounds good to me. Which API will you use?

**Comment by GajjarMiten** [comment]
For this demo application, I will use **Future.delayed()** which returns a list of Location objects.

**Comment by nisrulz** [comment]
Example app is added and merged.
