### ISSUE TITLE
json.decode(snapshot.data.toString); 

### ISSUE THREAD

**Issue by HassanMeer** [nisrulz/flutter-examples#30]
is that (sanpshot.data)  tha data is List type data variable ?

its not woeing as list data ..

**Comment by nisrulz** [comment]
It is json

https://github.com/nisrulz/flutter-examples/blob/master/load_local_json/data_repo/starwars_data.json

**Comment by nisrulz** [comment]
Closing this issue since it is more of a question. Already answered above.
