### ISSUE TITLE
How to use Navigator.pop

### ISSUE THREAD

**Issue by damon-zhu** [nisrulz/flutter-examples#31]
In my project, i use Navigator.push from A to B.
Now I want to back to A. So i use Navigator.pop in page B.
But the screen show black, i have to press the Back button on my Android Emulator to back to A.
![image](https://user-images.githubusercontent.com/12286304/52521667-8430bc80-2cb5-11e9-8133-635b557ad593.png)
![image](https://user-images.githubusercontent.com/12286304/52521672-8dba2480-2cb5-11e9-8386-891e7448a80d.png)

**Comment by LiuL0703** [comment]
```dart
Navigator.of(context).pop()
```

**Comment by nisrulz** [comment]
Closing this issue as @LiuL0703 answer is valid.
