### ISSUE TITLE
google_signin failing to build and run on flutter 1.2.1

### ISSUE THREAD

**Issue by bwfrieds** [nisrulz/flutter-examples#35]
Yesterday (monday april 29 2019), I cloned the repo and tried to build the "google_signin" project.  Eventually I got it building and running, after an hour of retesting.  I tested my changes only on a Pixel 2 connected device running Android P.   

I can build a pull request, if you like.  I plan to test the changes in a Nexus 5x emulator today. 

The problem seemed to be related to the latest versions of firebase_auth and google_sign_in.  I changed 6 files, although all changes may not be necessary for the fix.

**Comment by nisrulz** [comment]
Can you open a PR, so I can review? That would help speed up the process.

Thank you :)

**Comment by bwfrieds** [comment]
I probably did not do that correctly.

**Comment by nisrulz** [comment]
Yeah, I mean your PR does not have your changes but has the changes from another commit already in develop branch. 

https://github.com/nisrulz/flutter-examples/pull/36/commits/ed3f55c3293de29dbce97021ad2f119d1f78a180

**Comment by bwfrieds** [comment]
I'll just close this issue since I don't know what I'm doing.  Sorry.
