### ISSUE TITLE
using_theme floating button theme issue

### ISSUE THREAD

**Issue by dksharp** [nisrulz/flutter-examples#37]
floatingActionButton: new Theme(
        // override the accent color of theme for this widget only
        data: Theme.of(context).copyWith(accentColor: Colors.pinkAccent),
        child: new FloatingActionButton(
          onPressed: null,
          child: new Icon(Icons.add),
        ),
      ),

This is not working. Floating color button is set to lightGreenAccent.

**Comment by LoveqLRC** [comment]
same issue

**Comment by nisrulz** [comment]
I will take a look soon.

**Comment by nisrulz** [comment]
Based on the docs, it has changed: 

```floatingActionButton: Theme(
        data: Theme.of(context).copyWith(
          colorScheme:
              Theme.of(context).colorScheme.copyWith(secondary: Colors.yellow),
        ),
        child: FloatingActionButton(
          onPressed: null,
          child: Icon(Icons.add),
        ),
      ),```

https://flutter.dev/docs/cookbook/design/themes

**Comment by nisrulz** [comment]
<img width="600" alt="Screen Shot 2019-07-23 at 3 08 22 AM" src="https://user-images.githubusercontent.com/2096087/61675132-58e7da00-acf7-11e9-970a-367b00f16e69.png">
