### ISSUE TITLE
sample 'using_http_get' is not working

### ISSUE THREAD

**Issue by rollrat** [nisrulz/flutter-examples#48]
https://github.com/nisrulz/flutter-examples/blob/master/using_http_get/lib/main.dart
The URL (https://swapi.co/api/people) doesn't seem to be normal.

**Comment by lxjIDEA** [comment]
good

**Comment by koikatsu-user** [comment]
![](https://www.dogdrip.net/dvs/b/i/18/05/09/78/423/965/162/d21c9c551fc503861c9fbe005ed1003a.jpg)

**Comment by nisrulz** [comment]
The api was shutdown.

I see a new one has been put online: https://swapi.dev/

Will make this change and fix it.

**Comment by nisrulz** [comment]
Fixed.
