### ISSUE TITLE
PDF 

### ISSUE THREAD

**Issue by Tanmay1221** [nisrulz/flutter-examples#6]
Can u give any source code to view PDF in flutter

**Comment by guptaanirudha** [comment]
this might helpful https://github.com/flutter/flutter/issues/15406

**Comment by albo1337** [comment]
Hey @Tanmay1221 
You can use this one here [flutter_full_pdf_viewer](https://github.com/albo1337/flutter_full_pdf_viewer)
Feel free to give it a star so we can find some more user and help to improve the functionality of it.

Thx @guptaanirudha for sharing 👍

**Comment by guptaanirudha** [comment]
@albo1337 thanks for share the link, 

@Tanmay1221 let me know if you have any trouble, I would like to work with you to implement it. I am also learning flutter these days.

**Comment by nisrulz** [comment]
@albo1337 If you submit a PR with an example for using the same plugin, it would be a really nice addition to this repo. Inside your example folder, you can add a backlink to your repo for the plugin too :) 

Please do make sure you follow the PR guidelines in the Readme file for this repo.

**Comment by nisrulz** [comment]
I created an example request issue #18, which you can use.

**Comment by nisrulz** [comment]
Closing this issue as another issue is created to track this example in future.
