### ISSUE TITLE
Example Request: Image Editor App 

### ISSUE THREAD

**Issue by Gourav2000** [nisrulz/flutter-examples#74]
Hey Nishant,

I would like to contribute in this repo and work on this if its available.

**Comment by nisrulz** [comment]
Thank you for showing interest to contribute to this repo.

Could you provide details around 
- How you plan on building this example app?
- What package(s) you would use?

As long as you keep it highly focused and simple (split in files) for beginners I think you are good.

**Comment by Gourav2000** [comment]
Bascally i plan on adding two features to the app..

1- An Image cropping activity , where one can edit the image size, aspect ratio, rotation, zoom.
2- An image filter activity, where one can apply various photo  filters to the image.
 
the packages i plan on using are-
1.image cropper-[https://pub.dev/packages/image_cropper](https://pub.dev/packages/image_cropper)
2.image filter-[https://pub.dev/packages/photofilters](https://pub.dev/packages/photofilters)
3.gallery saver(to save the edited image in gallery )-[https://pub.dev/packages/gallery_saver](https://pub.dev/packages/gallery_saver),

**Comment by nisrulz** [comment]
Make sure to have the correct package name. Check contribution guidelines. Also make sure each functionality is split into proper files. This way it is easier to understand for beginners who come to this repo. Adding comments is appreciated.

**Comment by Gourav2000** [comment]
I have opened the PR and will be eagerly waiting for your review.

**Comment by nisrulz** [comment]
PR #75 was merged. Closing.
