### ISSUE TITLE
Requesting to contribute 

### ISSUE THREAD

**Issue by deveshgarg-max** [nisrulz/flutter-examples#83]
Hey, 
My name is Devesh Garg flutter developer, I have created more than 40 real-life projects and now want to contribute to this project I think there is no phone authentication with automatic OTP input. I can build it and make sure that it is proper user readable.
I also think multi-language support is also important so want to create its example too.

Thank you.

**Comment by nisrulz** [comment]
@deveshgarg-max you should open a new issue regarding each example you want to contribute. Take a look [here](https://github.com/nisrulz/flutter-examples/issues/21). Once you have created a dedicated issue for a specific example, we discuss the specifics. Once everything is finalised, you can open a PR.

Thanks

**Comment by nisrulz** [comment]
Closing this issue as it is irrelevant and not an issue.
