### ISSUE TITLE
Example Request: International Meals Recipes Mobile App

### ISSUE THREAD

**Issue by RohanSengupta326** [nisrulz/flutter-examples#90]
Hey Nishant,
I would like to contribute to this repo. I have created a mobile app that shows different meals of different countries and suited for different moods and their pictures and how to cook them with proper ingredients and step by step recipes.

I have split the code into different files. I will document the code and also use understandable variable names as much as possible. I have also formatted the code in every file.
I am using the latest version of flutter 2.5.1.

Can I create a PR ?

**Comment by nisrulz** [comment]
The contributor closed their PR. Closing this issue also.
