### ISSUE TITLE
Example Request : A basic Memes/News app

### ISSUE THREAD

**Issue by Sriraj-dev** [nisrulz/flutter-examples#97]
Hey Nishant,
I would like to contribute to this repo by adding an app which can show the latest news feed and memes to the users.

Can I make a PR on this under Hacktoberfest?

**Comment by nisrulz** [comment]
Yes go ahead.

Make sure to follow the package naming and directory structure of this repo.

**Comment by Sriraj-dev** [comment]
Yes, Thankyou.

**Comment by nisrulz** [comment]
Thank you @Sriraj-dev I'll take a look later in the day.

P.S: When opening a PR, always make sure to mention the issue number. I already did it for you in your PR description, but mentioning for future pointers :)

**Comment by Sriraj-dev** [comment]
Okay, @nisrulz I will do that from now.

Thankyou.
